### ISSUE TITLE
Here is the PCSX4ALL that comes with the rogue firmware for the PocketGo 2

### ISSUE THREAD

**Issue by iball** [SeongGino/RetroGame350-AppRepo#1] opened 2020-01-17 18:53 UTC
It was compiled specifically for the PocketGo 2 by the Rogue firmware creator I believe.
[pcsx4all.zip](https://github.com/SeongGino/RetroGame350-AppRepo/files/4078411/pcsx4all.zip)

**Comment by SeongGino** [comment] 2020-01-18 00:47
And what exactly does this provide that neither Soarqin/TonyJih's build nor Sauce's build can?

**Comment by iball** [comment] 2020-01-18 04:15
The emulator menu specifically says:

pcsx4all 2.4 for POCKET GO 2
Built on Jan 5 2020 at 19:57:16

Based upon the commits (https://github.com/Ninoh-FOX/POCKETGO2_PCSX4ALL) it was customized for the Pocket Go 2's control scheme to include the menu button opening the emulator menu instead of the power button like on the RG350 as well as configuring it to support the analog stick on the PG2.

**Comment by SeongGino** [comment] 2020-01-18 19:23
Honestly, I'll be hard-pressed to add yet another fork to PCSX4All when it could just as easily be merged into either of the two repos already linked. It ruins the relative streamlining of the repo if I add every fork possible of the same base game or emulator.

Also, it's known that the issue is related to the firmware of the PocketGo 2, and nothing to do with the emulator itself. Either using Stock, or updating to whatever latest firmware fork you use, is all I can suggest as someone who doesn't own this particular handheld.

**Comment by iball** [comment] 2020-01-19 01:24
"Also, it's known that the issue is related to the firmware of the PocketGo 2, and nothing to do with the emulator itself."  

What issue?

**Comment by SeongGino** [comment] 2020-01-19 17:58
> ...configuring it to support the analog stick on the PG2.

What you already said. Analog stick support is already provided in Soarqin's build, as tested by a few other users personally.

If there's nothing else to be said here, I'll be closing this issue off.

**Comment by SeongGino** [comment] 2020-01-21 18:33
Closing.

**Closed by SeongGino** 2020-01-21 18:33 UTC
